CSDS_395/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('resume_review.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume_review/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name="register"),
    path('', views.LoginView.as_view(), name="login"),
    path('home/', views.HomePageView.as_view(), name='home'),
    path('order/', views.OrderPageView.as_view(), name='order'),
    path('order_detail/', views.OrderDetailView.as_view(), name='order_detail'),
    path('user_profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('reviewer_profile/', views.ReviewerCardView.as_view(),
         name='reviewer_profile'),
    path('chat/', views.room, name='chat'),
    path('checkview', views.checkview, name='checkview'),
    path('send', views.send, name='send'),
    path('getMessages/', views.getMessages, name='getMessages'),
]

resume_review/models.py
from datetime import datetime, timedelta

from django.db import models
from django.contrib.auth.models import User

# Create your models here.
from django.utils import timezone

from resume_review import source_api
from datetime import datetime


class Account(models.Model):
    FRESHMEN = 'Freshmen'
    SOPHOMORE = 'Sophomore'
    JUNIOR = 'Junior'
    SENIOR = 'Senior'
    GRADUATE = 'Graduate'

    ACADEMIC_STANDING = [
        (FRESHMEN, 'Freshmen'),
        (SOPHOMORE, 'Sophomore'),
        (JUNIOR, 'Junior'),
        (SENIOR, 'Senior'),
        (GRADUATE, 'Graduate'),
    ]

    MAJOR = source_api.get_major_list()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    major = models.CharField(max_length=255, choices=MAJOR)
    academic = models.CharField(
        max_length=255, choices=ACADEMIC_STANDING)
    phone = models.CharField(max_length=12)
    create_at = models.DateField(auto_now=True)
    avatar = models.ImageField(
        upload_to='profile_pic', null=True, default='user.png')


class Reviewer(models.Model):
    account = models.ForeignKey(Account, on_delete=models.CASCADE)
    # maxprice 9999.99
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    specialized_field = models.CharField(max_length=255)
    self_intro = models.TextField()

    DELIVERY_TIME_CHOICES = [
        ('delivery_1', 'One week'),
        ('delivery_2', 'Two weeks'),
        ('delivery_3', 'Three weeks'),
        ('delivery_4', 'Four weeks or more'),
    ]
    rate = models.FloatField(default=0)
    delivery_time = models.CharField(
        max_length=255, choices=DELIVERY_TIME_CHOICES, default='delivery_1')


class Comment(models.Model):
    reviewer = models.ForeignKey(Reviewer, on_delete=models.CASCADE)
    account = models.ForeignKey(Account, on_delete=models.CASCADE, null=True)
    rate = models.CharField(max_length=255)
    comment = models.TextField(null=True)
    create_at = models.DateTimeField(null=False, default=timezone.now)


class Order(models.Model):
    PENDING = 'Pending'
    ACCEPT = 'Accepted'
    REJECT = 'Cancelled'
    COMPLETE = 'Completed'

    Order_State = [
        (PENDING, 'Pending'),
        (ACCEPT, 'Accepted'),
        (REJECT, 'Cancelled'),
        (COMPLETE, 'Completed'),
    ]
    account = models.ForeignKey(Account, on_delete=models.PROTECT)
    reviewer = models.ForeignKey(Reviewer, on_delete=models.PROTECT)
    create_at = models.DateTimeField(null=False, default=timezone.now)
    finished_at = models.DateTimeField(null=True, default=None)
    state = models.CharField(
        max_length=100, choices=Order_State, default=PENDING)
    resume = models.FileField(upload_to='resumes', null=True)


# can't migrate, not sure the reason
class Room(models.Model):
    name = models.CharField(max_length=1000)
    account = models.ForeignKey(Account, on_delete=models.PROTECT)
    reviewer = models.ForeignKey(Reviewer, on_delete=models.PROTECT)


class Message(models.Model):
    value = models.CharField(max_length=1000)
    date = models.DateTimeField(default=datetime.now, blank=True)
    account = models.ForeignKey(Account, on_delete=models.PROTECT)
    room = models.ForeignKey(Room, on_delete=models.PROTECT)

resume_review/forms.py
from django import forms
from django.contrib.auth import password_validation, authenticate
from django.contrib.auth.models import User
from django.forms import ValidationError, Select

from resume_review import source_api


class RegisterForm(forms.Form):
    username = forms.CharField(required=True, label='Username')
    email = forms.EmailField(required=True)
    password1 = forms.CharField(required=True, label='Password')
    password2 = forms.CharField(required=True, label='Verify password')

    def clean_email(self):
        email = self.cleaned_data['email']
        if not email.endswith('@case.edu'):
            raise ValidationError('Domain of email is not valid')
        return email

    def clean(self):
        password = self.cleaned_data.get('password1')
        re_password = self.cleaned_data.get('password2')
        username = self.cleaned_data.get('username')

        users = User.objects.filter(username=username)
        if len(users) > 0:
            self.add_error('username', "Username has existed")

        if not password == re_password:
            self.add_error('password2', "Passwords must match")

        return self.cleaned_data


class LoginForm(forms.Form):
    username = forms.CharField(required=True, label='Username')
    password = forms.CharField(required=True, label='Password')

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        if not user and username and password:
            users = User.objects.filter(username=username)
            if len(users) == 0:
                self.add_error('username', "Please enter the valid username.")
            else:
                self.add_error('password', "Please enter the valid password.")
        return self.cleaned_data


class UserProfileForm(forms.Form):
    first_name = forms.CharField(required=True, label='First Name', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter your first name'}))
    last_name = forms.CharField(required=True, label='Last Name', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter your last name'}))
    avatar = forms.ImageField(required=False, label='Avatar')
    phone_number = forms.CharField(required=True, label='Phone Number', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter your phone number'}))
    MAJOR_CHOICES = source_api.get_major_list()
    major = forms.ChoiceField(choices=MAJOR_CHOICES, required=True, label='Major',
                              widget=Select(attrs={"class": "form-select"}), initial='Accounting')
    self_intro = forms.CharField(required=False, widget=forms.Textarea(
        attrs={'class': 'form-control', 'placeholder': 'Enter your self introduction'}))
    price = forms.IntegerField(required=False)

    FRESHMEN = 'Freshmen'
    SOPHOMORE = 'Sophomore'
    JUNIOR = 'Junior'
    SENIOR = 'Senior'
    GRADUATE = 'Graduate'

    ACADEMIC_STANDING_CHOICES = [
        (FRESHMEN, 'Freshmen'),
        (SOPHOMORE, 'Sophomore'),
        (JUNIOR, 'Junior'),
        (SENIOR, 'Senior'),
        (GRADUATE, 'Graduate'),
    ]

    DELIVERY_TIME_CHOICES = [
        ('One week', 'One week'),
        ('Two weeks', 'Two weeks'),
        ('Three weeks', 'Three weeks'),
        ('Four weeks or more', 'Four weeks or more'),
    ]

    academic_standing = forms.ChoiceField(choices=ACADEMIC_STANDING_CHOICES, required=True, initial='Freshman', label='Academic Standing',
                                          widget=Select(attrs={"class": "form-select"}))

    delivery_time = forms.ChoiceField(choices=DELIVERY_TIME_CHOICES, required=True, initial='One week', label='Delivery Time',
                                          widget=Select(attrs={"class": "form-select"}))


class SearchForm(forms.Form):
    MAJOR_CHOICES = source_api.get_major_list()
    MAJOR_CHOICES.insert(0, ('All', 'All'))

    ALL = 'All'
    FRESHMEN = 'Freshmen'
    SOPHOMORE = 'Sophomore'
    JUNIOR = 'Junior'
    SENIOR = 'Senior'
    GRADUATE = 'Graduate'
    ACADEMIC_STANDING_CHOICES = [
        (ALL, 'All'),
        (FRESHMEN, 'Freshmen'),
        (SOPHOMORE, 'Sophomore'),
        (JUNIOR, 'Junior'),
        (SENIOR, 'Senior'),
        (GRADUATE, 'Graduate'),
    ]
    PRICE_CHOICE = [
        ('All', 'All'),
        ('1', '<20'),
        ('2', '20-50'),
        ('3', '50-100'),
        ('4', '>100'),
    ]

    name = forms.CharField(required=False, label='Name', widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Enter the name'}))
    # three choices to filter
    major = forms.ChoiceField(choices=MAJOR_CHOICES, required=True, label='Major',
                              widget=Select(attrs={"class": "form-select"}), initial='All')
    academic_standing = forms.ChoiceField(choices=ACADEMIC_STANDING_CHOICES, required=True, label='Standing',
                                          widget=Select(attrs={"class": "form-select"}), initial='All')
    price = forms.ChoiceField(choices=PRICE_CHOICE, required=True, label='Price',
                              widget=Select(attrs={"class": "form-select"}), initial='All')

class OrderDetailForm(forms.Form):
    resume = forms.FileField()

resume_review/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src = "{% static 'js/jquery.min.js' %}"></script>
    <script src = "{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src = "{% static 'js/navbar.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}" />
    <title>{% block title %}Title{% endblock %}</title>
</head>
<body>
<div id="sidebar">
    {% block sidebar %}
    <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand text-white" href="{% url 'home' %}"><i class="fa fa-graduation-cap fa-lg mr-2"></i>RESCUEME</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nvbCollapse" aria-controls="nvbCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="nvbCollapse">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item pl-1" id="home">
                        <a class="nav-link" href="{% url 'home' %}"><i class="fa fa-home fa-fw mr-1"></i>Home Page</a>
                    </li>
                    <li class="nav-item pl-1" id="order">
                        <a class="nav-link" href="{% url 'order' %}"><i class="fa fa-th-list fa-fw mr-1"></i>Order History</a>
                    </li>
                    <li class="nav-item pl-1" id="chat">
                        <a class="nav-link" href="{% url 'chat' %}"><i class="fa fa-comment fa-fw mr-1"></i>Chat</a>
                    </li>
                    <li class="nav-item pl-1" id="user_profile">
                        <a class="nav-link" href="{% url 'user_profile' %}"><i class="fas fa-id-badge fa-fw mr-1"></i>User Profile</a>
                    </li>
                </ul>
            </div>
            <a class="nav-link" id="logout-link" href="{% url 'login' %}"><i class="fas fa-sign-out-alt fa-fw mr-1"></i>Logout</a>
        </div>

    </nav>
    {% endblock %}
</div>

<div id="content">
    <div class="main-body">
    {% block content %}{% endblock %}
    </div>
</div>
</body>
</html>

resume_review/templates/card_example.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Review Card</title>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css">
        <link rel="stylesheet" href="{% static 'css/card.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    </head>

    <body>
        <section>
            <div class="container">
                <div class="card-wrapper">
                    <div class="card">
                        <img src="{% static 'img/tink.jpeg' %}" alt="card background" class="card-img">
                        <img src="{% static 'img/avatar.jpeg' %}" alt="profile image" class="profile-img">
                        <h1>Shark</h1>
                        <span class="fa fa-star checked"> 4.5</span>
                        <p class="about">
                            The IKEA store in Helsinki, Finland, was full of customers that day back in 1997. Being a textile technologist at Children’s IKEA at the time, Carina Ingelsten ran a course about safety for a group of IKEA co-workers.
                        </p>
                        <a href="#" class="btn">View</a>
                    </div>

                    <div class="card">
                        <img src="{% static 'img/tink.jpeg' %}" alt="card background" class="card-img">
                        <img src="{% static 'img/pikachu.jpeg' %}" alt="profile image" class="profile-img">
                        <h1>Pikachu</h1>
                        <span class="fa fa-star checked"> 3</span>
                        <p class="about">
                            Pikachu is a yellow mouse-like Pokémon with powerful electrical abilities. Pikachu is the best-known species of Pokémon, largely due to its appearance in the anime series.
                        </p>
                        <a href="#" class="btn">View</a>
                    </div>

                </div>
            </div>
        </section>
    </body>
</html> 

resume_review/templates/order_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}Order Details{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/order_detail.css' %}" />
<link rel="stylesheet" href="{% static 'css/rating.css' %}" />
<link rel="stylesheet" href="{% static 'css/track_order.css' %}" />
<script src = "{% static 'js/rating.js' %}"></script>
<script src = "{% static 'js/orderpage.js' %}"></script>

<form class="order-detail-form" id="order-detail-form" method="post" action="" enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    <input id="id_button" name="button" hidden>
    <input id="id_rate" name="rate" hidden>
    <input id="id_comment" name="comment" hidden>
    <input hidden value="{{current_account.first_name}} {{current_account.last_name}}" id='current-user'>

    <div class="container">
        <article class="card">
            <header class="card-header">
                <div class='row'>
                    <div class="col-sm-8" >
                        <div class="order-title"> <h5>Orders Details</h5></div>
                    </div>
                    <div class="col-sm-2" >
                        <a href="{% url 'order' %}" class="btn btn-primary order-btn" data-abc="true"> <i class="fas fa-chevron-circle-left"></i> Back</a>
                    </div>
                </div>
            </header>
            <div class="card-body">
                <h6>Order ID: #{{order.id}}</h6>
                <article class="card">
                    <div class="order-col-element" >
                        <table>
                            <tr>
                                <td class="table-header">Customer</td>
                                <td class="table-content" id='customer-name'>{{ order.account.first_name }} {{ order.account.last_name }}</td>
                                <td class="table-header">Reviewer</td>
                                <td id="reviewer-name" class="table-content">{{ order.reviewer.account.first_name }} {{ order.reviewer.account.last_name }}</td>
                            </tr>
                            <tr>

                                <td class="table-header">Start Time</td>
                                <td class="table-content">{{order.create_at}}</td>
                                <td class="table-header">Complete Time</td>
                                <td class="table-content">
                                    {% if order.finished_at %}
                                    {{order.finished_at}}
                                    {% endif %}
                                </td>
                            </tr>
                            <tr>
                                <td class="table-header">Status</td>
                                <td class="table-content">{{order.state}}</td>
                                <td class="table-header">Price</td>
                                <td class="table-content">${{ order.reviewer.price }}</td>
                            </tr>
                        </table>
                    </div>

                </article>
                <div id="order-state-hidden" hidden><span>{{order.state}}</span></div>
                <div class="progress-track" style="margin-top:50px;margin-bottom:50px">
                    <ul id="progressbar">
                        <li class="step0 active" id="step1"><span id="progress-one">Order Placed</span></li>
                        <li class="step0 active text-center" id="step2"><span style="text-align: center;" id="progress-two">Pending</span></li>
                        <li class="step0 text-center" id="step3"><span id="progress-three">Accepted</span></li>
                        <li class="step0 text-right" id="step4"><span id="progress-four">Completed</span></li>
                    </ul>
                </div>
                <hr>

                <button type="submit" class="btn btn-primary" id="accept">Accept Order</button>
                <button type="submit" class="btn btn-danger" id="cancel">Cancel Order</button>
                <button type="button" class="btn" data-toggle="modal" data-target="#exampleModal" id="ratingSection">
                    Rate the Reviewer
                </button>
                <button type="submit" class="btn btn-success" id="complete">
                    Complete Order
                </button>
            </div>
        </article>
        <div class="card" id="doc-card">
            <div class="card-body">
            <div class="sub-title">Documents</div>
            <div class="row mt-3">
                <!-- upload field -->

                <div class="file-upload col-9">
                    <div class="file-select">
                        <div class="file-select-button" id="fileName">Choose File</div>
                        <div class="file-select-name" id="noFile">No file chosen...</div>
                        {{ form.resume }}
                    </div>
                </div>
                <div class="col-3">
                    <div style="display: flex; justify-content: flex-end">
                        <button type="submit" class="btn btn-default order-btn" id="upload"><i class="fas fa-upload"></i> Upload</button>
                    </div>
                </div>
            </div>

            {% if order.resume %}

            <div class="row" style="margin-right:50px;margin-top:20px">
                <div class="col-9" id='download-files'>
                    {{ order.resume }}
                </div>
                <div class="col-3">
                    <div style="display: flex; justify-content: flex-end">
                        <button type="submit" class="btn btn-default order-btn" id="download"><i class="fas fa-download"></i> Download</button>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
    </div>

    <!-- Rating -->
    <section class='rating-field container-fluid'>
        <!-- Button trigger modal -->


        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Rating Form</h5>
                    </div>
                    <div class="modal-body">
                        <form id="ratingForm">
                            <div class="star">
                                <input type="radio" id="star5" name="star" value="5" hidden/>
                                <label for="star5" title="text"></label>
                                <input type="radio" id="star4" name="star" value="4" hidden/>
                                <label for="star4" title="text"></label>
                                <input type="radio" id="star3" name="star" value="3" hidden/>
                                <label for="star3" title="text"></label>
                                <input type="radio" id="star2" name="star" value="2" hidden/>
                                <label for="star2" title="text"></label>
                                <input type="radio" id="star1" name="star" value="1" hidden/>
                                <label for="star1" title="text"></label>
                            </div>
                            <br>
                            <textarea class="textComments" placeholder = "Leave Comments..." rows = "6" style="padding:10px"></textarea>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary" id="submit_rate">Submit</button>
                    </div>
                </div>
            </div>
        </div>
    </section>
</form>
{% endblock %}

resume_review/templates/register.html
{% load static %}

<!DOCTYPE html>
<html lang = "en">
<head>
    <meta charset = "UTF-8">
    <title> Login</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.5.1.min.js"></script>
    <script src = "{% static 'js/bootstrap.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/LoginStyle.css' %}" />
</head>

<body>
<section class="login-block" style="padding:100px;">
    <div class="container">
        <div class="row" style="height:600px;">
            <div class="col-md-8 banner-sec">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="{% static 'img/login_1.jpeg' %}" alt="First slide">
                            <div class="carousel-caption d-none d-md-block">
                                <div class="banner-text">
                                    <h2>Welcome to <br>CWRU Resume Review</h2>
                                    <p>CWRU Resume Review system is a platform for students and alumni to share their intelligence and resources and help each other improve career paths. Here, you can get professional opinions on your resume, which allows you to enhance your competitiveness.</p>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'img/login_2.jpeg' %}" alt="First slide">
                            <div class="carousel-caption d-none d-md-block">
                                <div class="banner-text">
                                    <h2>Our Protocol</h2>
                                    <p>Upload your resume and find matched students or alumni with experiences to provide professional suggestions.<br></p>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="{% static 'img/login_3.jpeg' %}" alt="First slide">
                            <div class="carousel-caption d-none d-md-block">
                                <div class="banner-text">
                                    <h2>Become a Reviewer?</h2>
                                    <p>If you are confident, become one of the reviewers to help your peers pursue their careers! Your experiences and efforts will be awarded through payroll and also improve your ratings in the system.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4 login-sec">
                <h2 class="text-center" style="color:#003658; margin-bottom: 10px;">Sign Up </h2>
                <form class="login-form" method="post" action="" novalidate>
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_username" class="text-uppercase">Username</label>
                        <input type="text" class="form-control" id="id_username" name="username">
                    </div>
                    <div class='login-err-msg'>
                    {% with field=form.username %}
                    {% for error in field.errors %}
                    {{ error }}
                    {% endfor %}
                    {% endwith %}
                    </div>
                    <div class="form-group">
                        <label for="id_email" class="text-uppercase">Email</label>
                        <input type="text" class="form-control" id="id_email" name="email">
                    </div>
                    <div class='login-err-msg'>
                    {% with field=form.email %}
                    {% for error in field.errors %}
                    {{ error }}
                    {% endfor %}
                    {% endwith %}
                    </div>
                    <div class="form-group">
                        <label for="id_password1" class="text-uppercase">Password</label>
                        <input type="password" class="form-control" id="id_password1" name="password1">
                    </div>
                    <div class='login-err-msg'>
                    {% with field=form.password1 %}
                    {% for error in field.errors %}
                    {{ error }}
                    {% endfor %}
                    {% endwith %}
                    </div>
                    <div class="form-group">
                        <label for="id_password2" class="text-uppercase">Verify Password</label>
                        <input type="password" class="form-control" id="id_password2" name="password2">
                    </div>
                    <div class='login-err-msg'>
                    {% with field=form.password2 %}
                    {% for error in field.errors %}
                    {{ error }}
                    {% endfor %}
                    {% endwith %}
                    </div>
                    <div class="sign-up-link"><a href="{% url 'login' %}"> Login to your account. </a></div>
                    <div class="form-check">
                        <button type="submit" class="btn btn-login float-right">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
</body>